#ifndef _M3C_INCGUARD_ASM_DIAGNOSTICS_DATA_H
#define _M3C_INCGUARD_ASM_DIAGNOSTICS_DATA_H

#include <m3c/core/diagnostics.h>

extern const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_INVALID_UTF8_SEQUENCES;
extern const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN;

#endif /* _M3C_INCGUARD_ASM_DIAGNOSTICS_DATA_H*/
