#ifndef _M3C_INCGUARD_ASM_DIAGNOSTICS_INFO_H
#define _M3C_INCGUARD_ASM_DIAGNOSTICS_INFO_H

#include <m3c/core/diagnostics.h>

extern const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_INVALID_ENCODING;
extern const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN;

#endif /* _M3C_INCGUARD_ASM_DIAGNOSTICS_INFO_H */
