#include <m3c/asm/diagnostics_info.h>

m3c_u8 const __M3C_ASM_STR_DIAGNOSTIC_INVALID_ENCODING[22] =
    "\x15"
    "invalid byte sequence";
m3c_u8 const __M3C_ASM_STR_DIAGNOSTIC_UNRECOGNIZED_TOKEN[19] =
    "\x12"
    "unrecognized token";

#define __M3C_ASM_DIAGNOSTIC_INFO_INVALID_ENCODING_ARGC 1
M3C_FmtArg __M3C_ASM_FMT_ARGS_INVALID_ENCODING[__M3C_ASM_DIAGNOSTIC_INFO_INVALID_ENCODING_ARGC] = {
    {M3C_FmtArgKind_LU8_ASCII, __M3C_ASM_STR_DIAGNOSTIC_INVALID_ENCODING}
};
const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_INVALID_ENCODING = {
    M3C_DIAGNOSTIC_DOMAIN_ASM,
    M3C_ASM_DIAGNOSTIC_ID_INVALID_ENCODING,
    M3C_SEVERITY_ERROR,
    {__M3C_ASM_DIAGNOSTIC_INFO_INVALID_ENCODING_ARGC, __M3C_ASM_FMT_ARGS_INVALID_ENCODING},
};

#define __M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN_ARGC 1
M3C_FmtArg
    __M3C_ASM_FMT_ARGS_UNRECOGNIZED_TOKEN[__M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN_ARGC] = {
        {M3C_FmtArgKind_LU8_ASCII, __M3C_ASM_STR_DIAGNOSTIC_UNRECOGNIZED_TOKEN}
};
const M3C_DiagnosticsInfo M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN = {
    M3C_DIAGNOSTIC_DOMAIN_ASM,
    M3C_ASM_DIAGNOSTIC_ID_UNRECOGNIZED_TOKEN,
    M3C_SEVERITY_ERROR,
    {__M3C_ASM_DIAGNOSTIC_INFO_UNRECOGNIZED_TOKEN_ARGC, __M3C_ASM_FMT_ARGS_UNRECOGNIZED_TOKEN},
};
